// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Convert an HTML buffer containing `len` UTF-8 bytes.
///
/// # Safety
/// `input` must reference `len` readable bytes. Free the result with `htm_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.UintPtr)
>()
external ffi.Pointer<ffi.Char> htm_convert(
  ffi.Pointer<ffi.Char> input,
  int len,
);

/// Convert HTML and extract embedded images into a JSON result.
///
/// # Safety
/// `input` must reference `len` readable bytes; non-null JSON must be NUL-terminated.
/// Free the result with `htm_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> htm_convert_with_inline_images(
  ffi.Pointer<ffi.Char> input,
  int len,
  ffi.Pointer<ffi.Char> options_json,
  ffi.Pointer<ffi.Char> image_config_json,
);

/// Convert HTML and return JSON with Markdown and selected metadata.
///
/// # Safety
/// `input` must reference `len` readable bytes; non-null JSON must be NUL-terminated.
/// Free the result with `htm_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> htm_convert_with_metadata(
  ffi.Pointer<ffi.Char> input,
  int len,
  ffi.Pointer<ffi.Char> options_json,
  ffi.Pointer<ffi.Char> metadata_config_json,
);

/// Convert HTML with optional JSON options.
///
/// # Safety
/// `input` must reference `len` readable bytes; non-null JSON must be NUL-terminated.
/// Free the result with `htm_free_string`.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> htm_convert_with_options(
  ffi.Pointer<ffi.Char> input,
  int len,
  ffi.Pointer<ffi.Char> options_json,
);

/// Release a string allocated by this library; a null pointer is accepted.
///
/// # Safety
/// `s` must be null or a live pointer returned by this library, freed exactly once.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void htm_free_string(ffi.Pointer<ffi.Char> s);
