// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.UintPtr)
>()
external ffi.Pointer<ffi.Char> htm_convert(
  ffi.Pointer<ffi.Char> input,
  int len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void htm_free_string(ffi.Pointer<ffi.Char> s);
